from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
# from django.core.files.storage import default_storage

from . import view

app_name = 'StaticFiles'


urlpatterns = [
    path("", view.showApps),
    path("home", view.MainHandler),
    path("login_page", view.login_page),
    path("resources", view.resources),
    path("mobile/resources", view.mobileResources),
    path("devicepicker", view.device_rec),
    path("mobile/devicepicker", view.mobileDevicepicker),
    path("nouser", view.NoUserHandler),
    path("mobile/nouser", view.mobileNoUserHandler),
    path("logout", view.Logout),
    path("mobile/login_page", view.mobileLogin),
    path("mobile/logout", view.mobileLogout),
    path("college_questions", view.collegeQ),
    path("mobile/college_questions", view.mobileCollegeQ),
    path("degree_questions", view.degree),
    path("mobile/degree_questions", view.mobileDegree),
    path("save", view.saver),
    path("mobile/save", view.mobileSaver),
    path("knowdegree", view.knowdegree),
    path("mobile/knowdegree", view.mobileKnowdegree),
    path("knowdevice", view.knowdevice),
    path("mobile/knowdevice", view.mobileknowdevice),
    path("knowcollege", view.knowcollege),
    path("mobile/knowcollege", view.mobileKnowcollege),
    path("mobile/home", view.mobileMain),
    path("test", view.test),
    path("engineeringSubQuestions", view.engineeringSubQuestions),
    path("mobile/engineeringSubQuestions", view.mobileEngineeringSubQuestions),
    path("about", view.about),
    path("mobile/about", view.mobileabout),
    path("gpaCalculator", view.gpaCalculator),
    path("mobile/gpaCalculator", view.mobileGPACalculator),
    path("ads.txt", view.Ads),
    path("withGoogle", view.withGoogle),
    path("login", view.loginBoth),
    path("mobile/withGoogle", view.mobileWithGoogle),
    path("mobile/Login", view.mLogin),
    path("xynsie", view.showData),
    path("showData", view.showData2),
    path("showData2", view.showData3),
    path("showData3", view.showData4),
    path("setData", view.setData),
    path("addNewUser", view.addNewUser),
    path("addGoogleNewUser", view.addGoogleNewUser),
    path("addAppleNewUser", view.addAppleNewUser),
    path("showAds", view.embeddedAdPage),
    path("jsonTest", view.jsonTest),
    path("TermsOfService", view.TermsOfService),
    path("PrivacyPolicy", view.PrivacyPolicy),
    path("mobile/ForgotPassword", view.mobileForgotPassword),
    path("ForgotPassword", view.ForgotPassword),
    path("ResetPassword", view.ResetPassword),
    path("mobile/ResetPassword", view.mobileResetPassword),
    path("/", view.MainHandler),
    path("mobile/", view.showApps),
    path("changeProfilePicture", view.changeProfilePicture),
    path("mobile/changeProfilePicture", view.mobileChangeProfilePicture),
    path("returnDegreeSelections", view.returnDegreeSelections),
    path("returnEngineeringSelections", view.returnEngineeringSelections),
    path("returnDeviceSelections", view.returnDeviceSelections),
    path("importantDates", view.importantDates),
    path("knowSupplies", view.knowSuppliesView),
    path("mobile/knowSupplies", view.mKnowSuppliesView),
    path("collegeSupplies", view.collegeSuppliesView),
    path("mobile/CollegeSupplies", view.mCollegeSuppliesView),
    path("admin/supplies", view.adminCollegeSupplies),
    path("mobile/admin/supplies", view.mobileAdminCollegeSupplies),
    path("public/collegeSupplies", view.collegeSupplies),
    path("buyOrSell", view.buyOrSell),
    path("buy/<str:college>", view.buyingPage),
    path("sell/<str:college>", view.sellingPage),
    path("sold/<str:college>", view.soldPage),
    path("updatedWebMessager", view.updatedWebMessaging),
    path("newMessage", view.newMessage),
    path("messenger", view.messengerPage),
    path("deleteListing", view.deleteListing),
    path("deleteListingApp", view.deleteListingApp),
    path("collegesListAPI", view.collegesListAPI)
    # path('', UploadView.as_view(), name='upload-image')
]

